package ansible

import (
	"fmt"
	"sort"
	"strings"

	"github.com/devnullvoid/pvetui/pkg/api"
)

// InventoryDefaults defines default SSH users for inventory generation.
type InventoryDefaults struct {
	NodeSSHUser string
	VMSSHUser   string
}

// InventoryHost captures one generated host entry.
type InventoryHost struct {
	Alias      string
	Target     string
	GroupNames []string
	Vars       map[string]string
}

// InventoryResult contains the final inventory text and generated host metadata.
type InventoryResult struct {
	Text  string
	Hosts []InventoryHost
}

// BuildInventory renders an INI-style Ansible inventory from Proxmox nodes and guests.
func BuildInventory(nodes []*api.Node, guests []*api.VM, defaults InventoryDefaults) InventoryResult {
	hosts := make([]InventoryHost, 0, len(nodes)+len(guests))
	groups := make(map[string][]InventoryHost)

	pushHost := func(host InventoryHost) {
		hosts = append(hosts, host)
		for _, group := range host.GroupNames {
			groups[group] = append(groups[group], host)
		}
	}

	for _, node := range nodes {
		if node == nil {
			continue
		}

		target := chooseHostTarget(node.IP, node.Name)
		if target == "" {
			continue
		}

		alias := uniqueAlias(hosts, "node_"+sanitizeIdentifier(node.Name))
		vars := map[string]string{
			"ansible_host":  target,
			"ansible_user":  defaults.NodeSSHUser,
			"pvetui_kind":   "node",
			"pvetui_node":   node.Name,
			"pvetui_online": fmt.Sprintf("%t", node.Online),
		}
		if node.SourceProfile != "" {
			vars["pvetui_source_profile"] = node.SourceProfile
		}

		groupNames := []string{"proxmox_nodes"}
		if node.Online {
			groupNames = append(groupNames, "running")
		} else {
			groupNames = append(groupNames, "stopped")
		}

		pushHost(InventoryHost{
			Alias:      alias,
			Target:     target,
			GroupNames: groupNames,
			Vars:       vars,
		})
	}

	for _, guest := range guests {
		if guest == nil {
			continue
		}

		target := chooseHostTarget(guest.IP, guest.Name)
		if target == "" {
			continue
		}

		aliasSeed := fmt.Sprintf("guest_%d_%s", guest.ID, sanitizeIdentifier(guest.Name))
		alias := uniqueAlias(hosts, aliasSeed)

		vars := map[string]string{
			"ansible_host":      target,
			"ansible_user":      defaults.VMSSHUser,
			"pvetui_kind":       "guest",
			"pvetui_guest_id":   fmt.Sprintf("%d", guest.ID),
			"pvetui_guest_type": guest.Type,
			"pvetui_status":     guest.Status,
			"pvetui_node":       guest.Node,
		}
		if guest.SourceProfile != "" {
			vars["pvetui_source_profile"] = guest.SourceProfile
		}
		if strings.TrimSpace(guest.Tags) != "" {
			vars["pvetui_tags"] = guest.Tags
		}

		groupNames := []string{"proxmox_guests", "by_node_" + sanitizeIdentifier(guest.Node)}
		switch guest.Type {
		case api.VMTypeQemu:
			groupNames = append(groupNames, "qemu")
		case api.VMTypeLXC:
			groupNames = append(groupNames, "lxc")
		}
		if strings.EqualFold(guest.Status, api.VMStatusRunning) {
			groupNames = append(groupNames, "running")
		} else {
			groupNames = append(groupNames, "stopped")
		}

		pushHost(InventoryHost{
			Alias:      alias,
			Target:     target,
			GroupNames: groupNames,
			Vars:       vars,
		})
	}

	return InventoryResult{
		Text:  renderInventory(groups),
		Hosts: hosts,
	}
}

func renderInventory(groups map[string][]InventoryHost) string {
	orderedGroups := make([]string, 0, len(groups))
	for group := range groups {
		orderedGroups = append(orderedGroups, group)
	}
	sort.Strings(orderedGroups)

	var builder strings.Builder
	builder.WriteString("# Generated by pvetui Ansible plugin\n")
	builder.WriteString("[all:vars]\n")
	builder.WriteString("pvetui_generated=true\n\n")

	for _, group := range orderedGroups {
		builder.WriteString("[")
		builder.WriteString(group)
		builder.WriteString("]\n")

		groupHosts := groups[group]
		sort.Slice(groupHosts, func(i, j int) bool {
			return groupHosts[i].Alias < groupHosts[j].Alias
		})

		for _, host := range groupHosts {
			builder.WriteString(host.Alias)
			builder.WriteString(" ")
			builder.WriteString(renderHostVars(host.Vars))
			builder.WriteString("\n")
		}

		builder.WriteString("\n")
	}

	return builder.String()
}

func renderHostVars(vars map[string]string) string {
	keys := make([]string, 0, len(vars))
	for key := range vars {
		if strings.TrimSpace(vars[key]) == "" {
			continue
		}
		keys = append(keys, key)
	}
	sort.Strings(keys)

	parts := make([]string, 0, len(keys))
	for _, key := range keys {
		parts = append(parts, fmt.Sprintf("%s=%s", key, quoteIfNeeded(vars[key])))
	}

	return strings.Join(parts, " ")
}

func quoteIfNeeded(value string) string {
	if value == "" {
		return `""`
	}

	needsQuotes := strings.ContainsAny(value, " \t;\"'")
	replacer := strings.NewReplacer(`\\`, `\\\\`, `"`, `\\"`)
	escaped := replacer.Replace(value)
	if needsQuotes {
		return `"` + escaped + `"`
	}

	return escaped
}

func chooseHostTarget(candidates ...string) string {
	for _, c := range candidates {
		trimmed := strings.TrimSpace(c)
		if trimmed != "" {
			return trimmed
		}
	}

	return ""
}

func sanitizeIdentifier(raw string) string {
	raw = strings.ToLower(strings.TrimSpace(raw))
	if raw == "" {
		return "unknown"
	}

	var out strings.Builder
	prevUnderscore := false
	for _, ch := range raw {
		isAlnum := (ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9')
		if isAlnum {
			out.WriteRune(ch)
			prevUnderscore = false
			continue
		}

		if !prevUnderscore {
			out.WriteRune('_')
			prevUnderscore = true
		}
	}

	sanitized := strings.Trim(out.String(), "_")
	if sanitized == "" {
		return "unknown"
	}

	return sanitized
}

func uniqueAlias(existing []InventoryHost, base string) string {
	if base == "" {
		base = "host"
	}

	alias := base
	idx := 1
	for hasAlias(existing, alias) {
		idx++
		alias = fmt.Sprintf("%s_%d", base, idx)
	}

	return alias
}

func hasAlias(hosts []InventoryHost, alias string) bool {
	for _, host := range hosts {
		if host.Alias == alias {
			return true
		}
	}

	return false
}
