version: 2

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"
  format: tar.gz

builds:
  # General build for all platforms except windows/amd64
  - id: pvetui
    main: ./cmd/pvetui
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64, 386]
    ignore:
      - goos: windows
        goarch: amd64
    ldflags:
      - -s -w
      - -X github.com/devnullvoid/pvetui/internal/version.version={{.Version}}
      - -X github.com/devnullvoid/pvetui/internal/version.commit={{.Commit}}
      - -X github.com/devnullvoid/pvetui/internal/version.buildDate={{.Date}}

  # Windows/amd64 build with extra compatibility settings
  - id: pvetui-windows-amd64
    main: ./cmd/pvetui
    env:
      - CGO_ENABLED=0
    goos: [windows]
    goarch: [amd64]
    goamd64: [v1]
    tags: [netgo, osusergo]
    ldflags:
      - -s -w
      - -X github.com/devnullvoid/pvetui/internal/version.version={{.Version}}
      - -X github.com/devnullvoid/pvetui/internal/version.commit={{.Commit}}
      - -X github.com/devnullvoid/pvetui/internal/version.buildDate={{.Date}}

archives:
  - id: default
    # ids: [pvetui, pvetui-windows-amd64]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - LICENSE
      - README.md
      - THIRD_PARTY_LICENSES.md
      - src: internal/vnc/novnc/LICENSE.txt
        dst: NOVNC_LICENSE.txt
      - src: internal/vnc/novnc/lib/pako/LICENSE
        dst: PAKO_LICENSE.txt

checksum:
  name_template: "checksums_{{ .Version }}.txt"

changelog:
  use: git
  filters:
    exclude:
      - "^chore:"
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

signs:
  - artifacts: checksum
    cmd: gpg2
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  draft: true
  prerelease: auto

announce:
  mastodon:
    # Whether its enabled or not.
    #
    # Templates: allowed (since v2.6).
    enabled: true
    # Message to use while publishing.
    #
    # Default: '{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}'.
    # Templates: allowed.
    message_template: "{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}"
    # Mastodon server URL.
    server: "{{ .Env.MASTODON_SERVER }}"
  bluesky:
    # Whether it's enabled or not.
    #
    # Templates: allowed (since v2.6).
    enabled: true
    # Message template to use while publishing.
    #
    # Default: '{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}'.
    # Templates: allowed.
    message_template: "{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}"
    # The username of the account that will post to Bluesky.
    username: "{{ .Env.BLUESKY_USERNAME }}"

# AUR Package (Binary)
aurs:
  - name: pvetui-bin
    homepage: "https://github.com/devnullvoid/pvetui"
    description: "A terminal user interface (TUI) for Proxmox VE"
    maintainers:
      - "devnullvoid <devnullvoid.space@gmail.com>"
    license: "MIT"
    private_key: "{{ .Env.AUR_PRIVATE_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/pvetui-bin.git"
    conflicts:
      - "pvetui"
      - "pvetui-git"
    provides:
      - "pvetui"
    depends:
      - "glibc"
    optdepends:
      - "kitty: Better terminal support"
      - "alacritty: Better terminal support"
    package: |-
      # Install binary
      install -Dm755 "./pvetui" "${pkgdir}/usr/bin/pvetui"

      # Install license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/pvetui/LICENSE"
      install -Dm644 "./THIRD_PARTY_LICENSES.md" "${pkgdir}/usr/share/licenses/pvetui/THIRD_PARTY_LICENSES.md"
      install -Dm644 "./NOVNC_LICENSE.txt" "${pkgdir}/usr/share/licenses/pvetui/noVNC/LICENSE.txt"
      install -Dm644 "./PAKO_LICENSE.txt" "${pkgdir}/usr/share/licenses/pvetui/noVNC/LICENSE.pako"

      # Install documentation
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/pvetui/README.md"
      install -Dm644 "./THIRD_PARTY_LICENSES.md" "${pkgdir}/usr/share/doc/pvetui/THIRD_PARTY_LICENSES.md"

# Homebrew Casks
homebrew_casks:
  - name: pvetui
    description: "Terminal user interface (TUI) for Proxmox VE"
    homepage: "https://github.com/devnullvoid/pvetui"
    license: "MIT"
    binaries:
      - "pvetui"
    repository:
      owner: "devnullvoid"
      name: "homebrew-pvetui"
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: "GoReleaser Bot"
      email: "noreply@github.com"
    caveats: |
      pvetui requires a Proxmox VE server to connect to.
      Run `pvetui --help` to see configuration options.
    hooks:
      post:
        install: 'system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pvetui"] if OS.mac?'
    custom_block: |
      # rubocop:disable Cask/StanzaOrder, Cask/StanzaGrouping

# Scoop Manifest
scoops:
  - name: pvetui
    description: "A terminal user interface (TUI) for Proxmox VE"
    homepage: "https://github.com/devnullvoid/pvetui"
    license: "MIT"
    repository:
      owner: "devnullvoid"
      name: "scoop-pvetui"
      token: "{{ .Env.SCOOP_GITHUB_TOKEN }}"
    commit_author:
      name: "GoReleaser Bot"
      email: "noreply@github.com"

# DEB Package
nfpms:
  - id: pvetui-deb
    description: "A terminal user interface (TUI) for Proxmox VE"
    homepage: "https://github.com/devnullvoid/pvetui"
    maintainer: "devnullvoid <devnullvoid.space@gmail.com>"
    license: "MIT"
    formats:
      - deb
    contents:
      - src: "{{ .ArtifactPath }}"
        dst: "/usr/local/bin/pvetui"
        type: "file"
      - src: "LICENSE"
        dst: "/usr/share/doc/pvetui/LICENSE"
        type: "doc"
      - src: "README.md"
        dst: "/usr/share/doc/pvetui/README.md"
        type: "doc"
      - src: "THIRD_PARTY_LICENSES.md"
        dst: "/usr/share/doc/pvetui/THIRD_PARTY_LICENSES.md"
        type: "doc"
      - src: "internal/vnc/novnc/LICENSE.txt"
        dst: "/usr/share/doc/pvetui/noVNC/LICENSE.txt"
        type: "doc"
      - src: "internal/vnc/novnc/lib/pako/LICENSE"
        dst: "/usr/share/doc/pvetui/noVNC/LICENSE.pako"
        type: "doc"
    overrides:
      deb:
        dependencies:
          - "libc6"
        recommends:
          - "kitty | alacritty"

  # RPM Package
  - id: pvetui-rpm
    description: "A terminal user interface (TUI) for Proxmox VE"
    homepage: "https://github.com/devnullvoid/pvetui"
    maintainer: "devnullvoid <devnullvoid.space@gmail.com>"
    license: "MIT"
    formats:
      - rpm
    contents:
      - src: "{{ .ArtifactPath }}"
        dst: "/usr/local/bin/pvetui"
        type: "file"
      - src: "LICENSE"
        dst: "/usr/share/doc/pvetui/LICENSE"
        type: "doc"
      - src: "README.md"
        dst: "/usr/share/doc/pvetui/README.md"
        type: "doc"
      - src: "THIRD_PARTY_LICENSES.md"
        dst: "/usr/share/doc/pvetui/THIRD_PARTY_LICENSES.md"
        type: "doc"
      - src: "internal/vnc/novnc/LICENSE.txt"
        dst: "/usr/share/doc/pvetui/noVNC/LICENSE.txt"
        type: "doc"
      - src: "internal/vnc/novnc/lib/pako/LICENSE"
        dst: "/usr/share/doc/pvetui/noVNC/LICENSE.pako"
        type: "doc"
    overrides:
      rpm:
        dependencies:
          - "glibc"
        suggests:
          - "kitty"
          - "alacritty"

# Docker Images (temporarily disabled until GHCR auth is fixed)
dockers: []
