version: 2

builds:
  # General build for all platforms except windows/amd64
  - id: pvetui
    main: ./cmd/pvetui
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64, 386]
    ignore:
      - goos: windows
        goarch: amd64
    ldflags:
      - -s -w
      - -X github.com/devnullvoid/pvetui/internal/version.version={{.Version}}
      - -X github.com/devnullvoid/pvetui/internal/version.commit={{.Commit}}
      - -X github.com/devnullvoid/pvetui/internal/version.buildDate={{.Date}}

  # Windows/amd64 build with extra compatibility settings
  - id: pvetui-windows-amd64
    main: ./cmd/pvetui
    env:
      - CGO_ENABLED=0
    goos: [windows]
    goarch: [amd64]
    goamd64: [v1]
    tags: [netgo, osusergo]
    ldflags:
      - -s -w
      - -X github.com/devnullvoid/pvetui/internal/version.version={{.Version}}
      - -X github.com/devnullvoid/pvetui/internal/version.commit={{.Commit}}
      - -X github.com/devnullvoid/pvetui/internal/version.buildDate={{.Date}}

archives:
  - id: default
    # ids: [pvetui, pvetui-windows-amd64]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [ 'tar.gz' ]
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums_{{ .Version }}.txt"

changelog:
  use: git
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

signs:
  - artifacts: checksum
    cmd: gpg2
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  draft: true
  prerelease: auto

# AUR Package (Binary)
aurs:
  - name: pvetui-bin
    homepage: "https://github.com/devnullvoid/pvetui"
    description: "A terminal user interface (TUI) for Proxmox VE"
    maintainers:
      - "devnullvoid <devnullvoid.space@gmail.com>"
    license: "MIT"
    conflicts:
      - "pvetui"
      - "pvetui-git"
    provides:
      - "pvetui"
    depends:
      - "glibc"
    optdepends:
      - "kitty: Better terminal support"
      - "alacritty: Better terminal support"
    package: |-
      # Install binary
      install -Dm755 "./pvetui" "${pkgdir}/usr/bin/pvetui"

      # Install license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/pvetui/LICENSE"

      # Install documentation
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/pvetui/README.md"

# AUR Package (Source)
aur_sources:
  - name: pvetui-git
    homepage: "https://github.com/devnullvoid/pvetui"
    description: "A terminal user interface (TUI) for Proxmox VE"
    maintainers:
      - "devnullvoid <devnullvoid.space@gmail.com>"
    license: "MIT"
    conflicts:
      - "pvetui-bin"
      - "pvetui"
    provides:
      - "pvetui"
    depends:
      - "go"
      - "git"
    makedepends:
      - "make"
    optdepends:
      - "kitty: Better terminal support"
      - "alacritty: Better terminal support"
    url_template: "https://github.com/devnullvoid/pvetui/archive/{{ .Tag }}.tar.gz"
    prepare: |-
      cd "${pkgname}-${pkgver}"
      go mod download
    build: |-
      cd "${pkgname}-${pkgver}"
      export CGO_CPPFLAGS="${CPPFLAGS}"
      export CGO_CFLAGS="${CFLAGS}"
      export CGO_CXXFLAGS="${CXXFLAGS}"
      export CGO_LDFLAGS="${LDFLAGS}"
      export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
      go build -ldflags="-w -s -linkmode=external -X github.com/devnullvoid/pvetui/internal/version.version=${pkgver}" ./cmd/pvetui
    package: |-
      cd "${pkgname}-${pkgver}"
      install -Dm755 ./pvetui "${pkgdir}/usr/bin/pvetui"
      install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/pvetui/LICENSE"
      install -Dm644 README.md "${pkgdir}/usr/share/doc/pvetui/README.md"

# Homebrew Casks
homebrew_casks:
  - name: pvetui
    description: "A terminal user interface (TUI) for Proxmox VE"
    homepage: "https://github.com/devnullvoid/pvetui"
    license: "MIT"
    binary: "pvetui"
    repository:
      owner: "devnullvoid"
      name: "homebrew-pvetui"
    commit_author:
      name: "GoReleaser Bot"
      email: "noreply@github.com"
    caveats: |
      pvetui requires a Proxmox VE server to connect to.
      Run 'pvetui --help' to see configuration options.
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pvetui"]
          end

# Scoop Manifest
scoops:
  - name: pvetui
    description: "A terminal user interface (TUI) for Proxmox VE"
    homepage: "https://github.com/devnullvoid/pvetui"
    license: "MIT"
    repository:
      owner: "devnullvoid"
      name: "scoop-pvetui"
    commit_author:
      name: "GoReleaser Bot"
      email: "noreply@github.com"

# DEB Package
nfpms:
  - id: pvetui-deb
    description: "A terminal user interface (TUI) for Proxmox VE"
    homepage: "https://github.com/devnullvoid/pvetui"
    maintainer: "devnullvoid <devnullvoid.space@gmail.com>"
    license: "MIT"
    formats:
      - deb
    contents:
      - src: "{{ .ArtifactPath }}"
        dst: "/usr/local/bin/pvetui"
        type: "file"
      - src: "LICENSE"
        dst: "/usr/share/doc/pvetui/LICENSE"
        type: "doc"
      - src: "README.md"
        dst: "/usr/share/doc/pvetui/README.md"
        type: "doc"
    overrides:
      deb:
        dependencies:
          - "libc6"
        recommends:
          - "kitty | alacritty"

  # RPM Package
  - id: pvetui-rpm
    description: "A terminal user interface (TUI) for Proxmox VE"
    homepage: "https://github.com/devnullvoid/pvetui"
    maintainer: "devnullvoid <devnullvoid.space@gmail.com>"
    license: "MIT"
    formats:
      - rpm
    contents:
      - src: "{{ .ArtifactPath }}"
        dst: "/usr/local/bin/pvetui"
        type: "file"
      - src: "LICENSE"
        dst: "/usr/share/doc/pvetui/LICENSE"
        type: "doc"
      - src: "README.md"
        dst: "/usr/share/doc/pvetui/README.md"
        type: "doc"
    overrides:
      rpm:
        dependencies:
          - "glibc"
        suggests:
          - "kitty"
          - "alacritty"

# Docker Images
dockers:
  - image_templates:
      - "ghcr.io/devnullvoid/pvetui:{{ .Version }}"
      - "ghcr.io/devnullvoid/pvetui:latest"
    dockerfile: "Dockerfile"
    use: "buildx"
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - LICENSE
      - README.md
