Source ./demo/common.tape
Sleep 3s
Type "m"
Sleep 1s
Enter
Sleep 1s
Type "htop"
Enter
Sleep 5s
Type "q"
Sleep 500ms
Type "exit"
Enter
Sleep 500ms
Enter
Sleep 1s
Type "]"
Sleep 500ms
Type@500ms "jjjj"
Sleep 1s
Type@500ms "/nix"
Enter
Sleep 500ms
Type "jj"
Sleep 100ms
Type "l"
Sleep 100ms
Type@500ms "jjjjjjjjj"
Sleep 500ms
Type "m"
Sleep 1s
Type "h"
Sleep 500ms
Type "]"
Sleep 2s
Type "q"
Sleep 200ms
Output demo/demo.gif
